gui:
  border: single
  sidePanelWidth: 0.333
  tabWidth: 2
  theme:
    activeBorderColor:
      - yellow
    inactiveBorderColor:
      - default
    selectedLineBgColor:
      - "#3B4252"
  authorColors:
    "Matthew Wagerfield": "yellow"
