gui:
  border: single
  sidePanelWidth: 0.333
  tabWidth: 2
  theme:
    activeBorderColor:
      - cyan
    inactiveBorderColor:
      - default
    selectedLineBgColor:
      - reverse
  authorColors:
    "Matthew Wagerfield": "yellow"
