gui:
  border: single
  sidePanelWidth: 0.333
  tabWidth: 2
  theme:
    activeBorderColor:
      - blue
    inactiveBorderColor:
      - "#859289"
    selectedLineBgColor:
      - reverse
  authorColors:
    "Matthew Wagerfield": "yellow"
