# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default
gui:
  border: single
  sidePanelWidth: 0.333
  tabWidth: 2
  theme:
    activeBorderColor:
      - blue
    inactiveBorderColor:
      - gray
    selectedLineBgColor:
      - reverse
  authorColors:
    "Matthew Wagerfield": "yellow"
