# vim:ft=kitty

# name: Everforest Dark
# author: Sainnhe Park
# url: https://github.com/sainnhe/everforest
# license: MIT

background              #2d353b
foreground              #d3c6aa

selection_background    #475258
selection_foreground    none

cursor                  #d3c6aa
cursor_text_color       background

url_color               #7fbbb3

active_border_color     #3d484d
inactive_border_color   #3d484d

bell_border_color       #e69875
visual_bell_color       none

tab_bar_margin_color    #232a2e
tab_bar_background      #232a2e
inactive_tab_background #3d484d
inactive_tab_foreground #9da9a0
active_tab_background   #d3c6aa
active_tab_foreground   #2d353b

# black
color0                  #232a2e
color8                  #3d484d

# red
color1                  #e67e80
color9                  #e67e80

# green
color2                  #a7c080
color10                 #a7c080

# orange & yellow
color3                  #e69875
color11                 #dbbc7f

# blue
color4                  #7fbbb3
color12                 #7fbbb3

# magenta
color5                  #d699b6
color13                 #d699b6

# cyan
color6                  #83c092
color14                 #83c092

# white
color7                  #7a8478
color15                 #9da9a0
