# vim:ft=kitty

# name: GitHub Light
# author: GitHub
# upstream: https://github.com/primer/github-vscode-theme
# license: MIT

background              #FFFFFF
foreground              #1F2328

selection_background    #DDF4FF
selection_foreground    none

cursor                  #0969DA
cursor_text_color       background

url_color               #0969DA

active_border_color     #D1D9E0
inactive_border_color   #D1D9E0

bell_border_color       #BF8700
visual_bell_color       none

tab_bar_margin_color    #D1D9E0
tab_bar_background      #F0F3F6
inactive_tab_background #F6F8FA
inactive_tab_foreground #57606A
active_tab_background   #FFFFFF
active_tab_foreground   #24292F

# primerText   #24292F - Default Foreground
# primerMuted  #57606A - Muted Foreground
color0         #24292F
color8         #57606A

# primerRed    #CF222E - Diagnostic Error, Git Delete
# primerRed2   #A40E26 - Strong Error
color1         #CF222E
color9         #A40E26

# primerGreen  #116329 - Strings, Git Add
# primerGreen2 #1A7F37 - Bright Success
color2         #116329
color10        #1A7F37

# primerBrown  #953800 - Constants, Imports, Booleans
# primerYellow #BF8700 - Diagnostic Warning, Git Change
color3         #953800
color11        #BF8700

# primerBlue   #0969DA - Functions, Links, Selection
# primerBlue2  #218BFF - Bright Accent
color4         #0969DA
color12        #218BFF

# primerPurple #8250DF - Statements and Keywords
# primerPink   #BF3989 - Numbers, Standout Specials
color5         #8250DF
color13        #BF3989

# primerCyan   #1B7C83 - Types, Diagnostic Info
# primerCyan2  #3192AA - Bright Info
color6         #1B7C83
color14        #3192AA

# primerSubtle #6E7781 - Secondary Foreground
# primerQuiet  #8C959F - Tertiary Foreground
color7         #E7EAEE
color15        #F6F8FA
