# vim:ft=kitty

# name: Kanagawa
# author: Tommaso Laurenzi
# upstream: https://github.com/rebelot/kanagawa.nvim
# license: MIT

background              #1F1F28
foreground              #DCD7BA

selection_background    #223249
selection_foreground    none

cursor                  #DCD7BA
cursor_text_color       background

url_color               #7FB4CA

active_border_color     #363646
inactive_border_color   #363646

bell_border_color       #D7A657
visual_bell_color       none

tab_bar_margin_color    #16161D
tab_bar_background      #16161D
inactive_tab_background #2A2A37
inactive_tab_foreground #727169
active_tab_background   #7E9CD8
active_tab_foreground   #1F1F28

# sumiInk0     #16161D - Dark Background (statuslines and floating windows)
# sumiInk1     #1F1F28 - Default Background
# sumiInk2     #2A2A37 - Lighter Background (colorcolumn, folds)
# sumiInk3     #363646 - Lighter Background (cursorline)
color0         #16161D
color8         #363646

# autumnRed    #C34043 - Git Delete
# samuraiRed   #E82424 - Diagnostic Error
# waveRed      #E46876 - Standout Specials 1
# peachRed     #FF5D62 - Standout Specials 2
color1         #E46876
color9         #FF5D62

# autumnGreen  #76946A - Git Add
# springGreen  #98BB6C - Strings
color2         #98BB6C
color10        #98BB6C

# autumnYellow #DCA561 - Git Change
# carpYellow   #E6C384 - Identifiers
# roninYellow  #FF9E3B - Diagnostic Warning
# surimiOrange #FFA066 - Constants, Imports, Booleans
color3         #E6C384
color11        #DCA561

# dragonBlue   #658594 - Diagnostic Hint
# crystalBlue  #7E9CD8 - Functions & Titles
# springBlue   #7FB4CA - Specials & Builtin Functions
color4         #7E9CD8
color12        #7FB4CA

# oniViolet    #957FB8 - Statements and Keywords
# sakuraPink   #D27E99 - Numbers
color5         #957FB8
color13        #D27E99

# waveAqua1    #6A9589 - Diagnostic Info
# waveAqua2    #7AA89F - Types
color6         #6A9589
color14        #7AA89F

# fujiWhite    #DCD7BA - Default Foreground
# oldWhite     #C8C093 - Dark Foreground
color7         #C8C093
color15        #DCD7BA
