# Yazi Theme - ANSI adaptive
# https://yazi-rs.github.io/docs/configuration/theme

[flavor]
light = "ansi-light"
dark  = "ansi-dark"

[mgr]
cwd             = { fg = "reset" }
find_position   = { fg = "magenta", italic = false, underline = false, bold = true }
marker_marked   = { fg = "magenta", bg = "magenta" }
marker_selected = { fg = "blue", bg = "blue" }
count_selected  = { fg = "black", bg = "blue" }
marker_cut      = { fg = "red", bg = "red" }
count_cut       = { fg = "black", bg = "red" }
border_symbol   = " "

[indicator]
padding     = { open = "█", close = "█" }
parent      = { reversed = true, bold = true }
current     = { reversed = true, bold = true }

[tabs]
active      = { fg = "reset", bg = "reset", reversed = true }
sep_outer   = { open = " ", close = " " }
sep_inner   = { open = "", close = "" }

[mode]
normal_main = { fg = "reset", bg = "reset", bold = true, reversed = true }
select_main = { fg = "black", bg = "magenta", bold = true }
unset_main  = { fg = "black", bg = "red", bold = true }

[status]
sep_left    = { open = "", close = "" }
sep_right   = { open = "", close = "" }

[which]
desc        = { fg = "reset" }
separator   = " -> "
cols        = 2

[input]
border = { fg = "gray" }
title  = { fg = "reset" }

[pick]
border = { fg = "gray" }
title  = { fg = "reset" }

[spot]
border   = { fg = "gray" }
title    = { fg = "reset" }
tbl_cell = { fg = "black", bg = "white", bold = true }

[confirm]
border = { fg = "gray" }
title  = { fg = "red" }

[tasks]
border = { fg = "gray" }
title  = { fg = "reset" }

[cmp]
border = { fg = "gray" }
title  = { fg = "reset" }

[filetype]
rules = [
  { fg = "reset", url = "*"  }, # files
  { fg = "reset", url = "*/" }, # folders
]
