[mgr]
cwd            = { fg = "white" }
marker_marked  = { fg = "magenta", bg = "magenta" }
count_selected = { fg = "black", bg = "yellow" }
count_copied   = { fg = "black", bg = "green" }
count_cut      = { fg = "black", bg = "red" }
border_style   = { bg = "black" }
border_symbol  = " "

[indicator]
preview     = { underline = false }
padding     = { open = "█", close = "█" }

[tabs]
active      = { fg = "black", bg = "green" }
inactive    = { fg = "white", bg = "black" }
sep_outer   = { open = " ", close = " " }
sep_inner   = { open = "", close = "" }

[mode]
normal_main = { fg = "black", bg = "blue"  }
normal_alt  = { fg = "white", bg = "black" }
select_main = { fg = "black", bg = "magenta" }
select_alt  = { fg = "white", bg = "black" }
unset_main  = { fg = "black", bg = "red"   }
unset_alt   = { fg = "white", bg = "black" }

[status]
overall     = { fg = "white", bg = "#232A2E" }
sep_left    = { open = "", close = "" }
sep_right   = { open = "", close = "" }

[which]
mask        = { bg = "black" }
cand        = { fg = "yellow" }
desc        = { fg = "reset" }
separator   = " -> "

[help]
on          = { fg = "yellow" }
run         = { fg = "white" }
desc        = { fg = "white" }
footer      = { fg = "white", bg = "#232A2E" }

[icon]
conds = []
globs = []
files = []
dirs  = []
exts  = []
